services:
  openssh-server:
    image: linuxserver/openssh-server:latest
    container_name: music-server
    hostname: music-server
    env_file: server/.env.server
    volumes:
      - ./server/config:/config
      # TODO: inherit from linuxserver/openssh-server Dockerfile
      # and add `apk install rsync` as a build step
      - ./server/custom-cont-init.d:/custom-cont-init.d
      - ./music:/music
    ports:
      - ${SSH_PORT}:2222
    healthcheck:
      test: nc -zv 127.0.0.1 2222
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  ssh-tunnel:
    build: tunnel
    container_name: music-server-tunnel
    env_file: tunnel/.env.tunnel
    network_mode: "service:openssh-server"
    restart: unless-stopped
    healthcheck:
      test: "[ $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].config.addr') == 'localhost:2222' ]"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  telegram-bot:
    build: telegram_bot
    container_name: music-server-bot
    env_file: telegram_bot/.env.bot
    network_mode: "service:openssh-server"
    volumes:
      - ./music:/music
    depends_on:
      openssh-server:
        condition: service_healthy
      ssh-tunnel:
        condition: service_healthy
    restart: unless-stopped
