services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    # TODO: remove CONTAINER_NAME and HOSTNAME from .env on actual host
    container_name: music-server
    hostname: music-server
    env_file: .env.server
    volumes:
      - ./server/config:/config
      # TODO: inherit from linuxserver/openssh-server Dockerfile
      # and add `apk install rsync` as a build step
      - ./server/custom-cont-init.d:/custom-cont-init.d
      - ./music:/music
    ports:
      - 3008:2222
    restart: unless-stopped

  telegram-bot:
    image: music-server-bot:latest
    container_name: music-server-bot
    hostname: music-server-bot-host
    env_file: .env.bot
    volumes:
      - ./music:/music
    restart: unless-stopped
