services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    # TODO: remove CONTAINER_NAME and HOSTNAME from .env on actual host
    container_name: music-server
    hostname: music-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC+8
      - PUBLIC_KEY_DIR=${PUBLIC_KEY_DIR}
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      - USER_NAME=${USER_NAME}
      - LOG_STDOUT=
    volumes:
      - ./server/config:/config
      # TODO: inherit from linuxserver/openssh-server Dockerfile
      # and add `apk install rsync` as a build step
      - ./server/custom-cont-init.d:/custom-cont-init.d
      - ${MUSIC_DIR}:/music
    ports:
      - 3008:2222
    restart: unless-stopped

  telegram-bot:
    image: music-server-bot:latest
    container_name: music-server-bot
    hostname: music-server-bot-host
    volumes:
      - ${MUSIC_DIR}:/music
    restart: unless-stopped
